docs/contents.rst.inc
docs/scenarios/json.rst

Still a work in progress for this issue. Please comment and review
Be gentle my first pull request

add initial JSON section

---

docs/contents.rst.inc
docs/writing/logging.rst

This is in reference to Issue 336 -- [No section on logging?](https://github.com/kennethreitz/python-guide/issues/336)
It is a first attempt, written in a separate file, and inserted between the Testing and Gotchas section on the Writing page. Thank you for suggestions!

Logging section

---

docs/scenarios/json.rst

Thanks for merging my first PR @kennethreitz !
sorry for leaving my original PR hanging after it had been reviewed
I've done some more improvements to the section with help from mplewis (https://github.com/mplewis )

Improvements to the JSON section

---

docs/starting/install/osx.rst

The latest version of Mac OS X is Yosemite.It isn't Mavericks.

The latest version of Mac OS X is Yosemite.

---

docs/dev/virtualenvs.rst

refer https://github.com/kennethreitz/python-guide/issues/483

virtualenvwrapper-win

---

docs/intro/learning.rst

It really helped me as a beginner hence the recommendation. Also added an extra space (where necessary) in between each suggestion to make it more clear for other people who edit. Thanks!

Python course for beginners

---

docs/writing/style.rst

Removed broken link to Zen of Python

---

docs/scenarios/gui.rst

Change pyside link to
https://wiki.qt.io/Category:LanguageBindings::PySide::Downloads

pyside link

---

docs/starting/which-python.rst

Kept up-to-date unlike Armin's blog post on the subject.

Point to the Python 3 porting HOWTO

---

docs/shipping/freezing.rst
docs/shipping/packaging.rst

I've tried to describe why you would choose freezing versus packaging versus creating a Linux distribution package, and the relative advantages and disadvantages of each method.
My intent is to add more content on the Freezing page once this commit is accepted, so I can hear your feedback before doing any further work.

Intro paras for Freezing and Packaging your code

---

docs/starting/install/osx.rst

Minor Edit

---

Readme.rst

Update the Readme.rst

---

docs/intro/documentation.rst
docs/scenarios/admin.rst
docs/scenarios/gui.rst
docs/shipping/freezing.rst
docs/shipping/packaging.rst
docs/starting/pip-virtualenv.rst
docs/writing/documentation.rst
docs/writing/style.rst

just a little help for your project

fixed a few typos

---

docs/writing/structure.rst

Nothing major here... just tidying up.

Typo and grammar fixes.

---

docs/dev/env.rst

Installs IPython and also dependencies for IPython notebook.

IPython install edit

---

docs/writing/style.rst

Standardized spelling to match Oxford spelling throughout the rest of the text. Changed 'recognised' to 'recognized'.

Corrected typo.

---

docs/shipping/freezing.rst

There's a new major release that adds Python 3 compatibility.

PyInstaller is py3 compatible now

---

docs/writing/gotchas.rst

This is follow up PR for #556, since original submitter did not respond I thought of sending this. Feel free to close this.
:beers:

Update `gotchas.rst` to make the sentence simpler

---

docs/starting/install/linux.rst

* Removes redundant language.
* Helps user understand which version of Python & pip are installed.
* Link to modern way of installing pip & setuptools
Fixes  #589

 Improve documentation for Linux Installation

---

docs/dev/env.rst

Edited env.rst to remove duplication of virtualenv section and provide better flow to the actual virtualenv section.
Fix for #123

virtualenv duplicate fix

---

docs/writing/reading.rst

This project is very easy to read, is well written, well formatted (they use autopep8).
I think it's a very good example for reading.

Add Diamond python project - Metrics collector

---

docs/scenarios/imaging.rst

Added an example section to the imaging.rst file as well as a link to a Pillow tutorial.

Added in examples and link to tutorial for imaging.rst.

---

docs/intro/learning.rst

I found this tool helpful when I started to learn how to code and I thought that this should be on the list.

Added Online Python Tutor

---

Readme.rst

Some small corrections in README.

Some Corrections in README

---

docs/shipping/freezing.rst

I added some explanation, examples and links on using PyInstaller in OS X.

Added PyInstaller section for OS X

---

docs/intro/learning.rst

Elaborated on the Codecademy description so it specifies that the user's code is interpreted in-browser for feedback on the user's work. This part wasn't specified very well in the previous description.

Added Codecademy description

---

docs/intro/learning.rst

fullstackpython for web development

Add misc learning resource

---

docs/scenarios/serialization.rst

Wanted to add some documentation about other serialization modules for Python, but figure that it might make sense to have a single "serialization" file that contains info on Pickle, etc. I would also think it would make sense to combine this with the XML and JSON files. What do others think?

Added serialization.rst file to scenarios.

---

docs/writing/structure.rst

I've noticed that there was no mention of context managers in the guide. Personally I've found them to be a way underrated mechanism to manage complexity even in small projects.

Adds context manager section to structure.rst

---

docs/scenarios/gui.rst

PyGObject (Python GTK+ 3 bindings) section has been added.

PyGObject section added

---

docs/writing/structure.rst

Fix pip requirements link

---

docs/scenarios/web.rst

Remove inaccurate comparison of Pyramid to Django.

---

docs/scenarios/web.rst

use correct URL for Pyramid

---

docs/writing/documentation.rst

#678 Link to pep 257 about docstrings and some docs already cover docstrings

link to pep 257

---

docs/scenarios/db.rst
docs/writing/structure.rst
docs/writing/style.rst

Updated a few typos in the repo.

Fix a few typos

---

docs/writing/reading.rst

Tenants are people who pay rent; tenets are principles or beliefs.

changed "tenants" to "tenets"

---

docs/intro/news.rst

A weekly overview of the most popular Python news, articles and packages

Add 'Awesome Python Newsletter' from LibHunt

---

docs/scenarios/speed.rst

speed.rst: PEP8 in examples

---

docs/writing/style.rst

I cleaned up the intro paragraphs of style.rst a bit.

Clean up of intro paragraphs for clarity.

---

docs/dev/env.rst

[Visual Studio Code](https://code.visualstudio.com) is a very lightweight, free and cross platform IDE.
This is MIT licensed (open source).
The [Python extension[(https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) turns this IDE into an excellent Python Development Environment.
This too is open sourced and MIT licensed.
Features include (for python development) include:
- Integrated GIT
- Tasks
- Local and remote debugging
- Linting (multiple linters)
- Intellisense (signatures, auto completion, etc)
- Code navigation (find references, go to def, etc)
etc

updated to include a reference to VS Code

---

docs/writing/structure.rst

start-project should be startproject
https://docs.djangoproject.com/en/1.9/ref/django-admin/#django-admin-startproject

Update startproject in example

---

docs/writing/tests.rst

A bit of clean up on tests.rst and wrap of text in last para to accommodate change.
Q: is there an external source about unit testing that we could link to? Just think that folks unfamiliar with the concept might appreciate the resource.

Clean up of tests.rst

---

docs/scenarios/cli.rst

[The old URL](http://mercurial.selenic.com/) no longer works 😢 
Thanks!

Update link to Mercurial site

---

docs/scenarios/ml.rst

@kennethreitz @PaulReiber Started on a doc for Machine Learning, added some basic stuff about scikit-learn et al. Solves #755. 
Please review, would be happy to make edits if needed :)

added machine learning docs

---

docs/scenarios/cli.rst

Add cement to cli frameworks

---

docs/writing/documentation.rst

I added some words about commonly used patterns, as well as touching on what sphinx does and how it turns your code into documentation automatically. Also added a couple links to useful articles if people want to read further. Relevant to #678 and #699

Wrote up a couple examples for docstrings

---

docs/contents.rst.inc

Reverts kennethreitz/python-guide#747

Revert "Update contents.rst.inc"

---

docs/starting/install/win.rst

Update link for ez_setup.py, in python-guide/docs/starting/install/win.rst file, because the old link was broken.

Update link for ez_setup.py

---

docs/dev/env.rst

Resolve the missing space from issue #772.

Fix missing space

---

docs/writing/tests.rst

update tox docs url, the old page does not exist yet.

update tox docs url

---

docs/scenarios/scrape.rst

Update W3Schools link to the XPath Tutorial.

---

docs/dev/env.rst
docs/dev/virtualenvs.rst
docs/intro/learning.rst
docs/intro/news.rst
docs/scenarios/clibs.rst
docs/scenarios/speed.rst
docs/scenarios/web.rst
docs/shipping/freezing.rst
docs/shipping/packaging.rst
docs/starting/install3/osx.rst

https://travis-ci.org/kennethreitz/python-guide/builds/204641280

Fix build warnings

---

docs/scenarios/ci.rst

I think this make more sense, since all of these options are explained there.

Link to **Python** docs of travis.

---

docs/_templates/sidebarintro.html
docs/_templates/sidebarlogo.html

The pt_BR team started the translation!

Language pt_BR - Fixes #788

---

docs/intro/news.rst

@kennethreitz @mikeckennedy @okken Let me know if the descriptions are apt.

add Talk Python & Python Bytes podcasts to news

---

docs/starting/installation.rst

Add ref to installation.rst so it can be referenced on others sphinx documentations.

Add ref to installation.rst

---

docs/contents.rst.inc

fix indent

---

docs/dev/virtualenvs.rst
docs/writing/gotchas.rst

Added an internal link to existing Version Control Ignores section in gotchas.rst and used it in the virtualenvs.rst page.

add internal link to version control ignores

---

docs/dev/virtualenvs.rst

change $PROJECT_HOME to $WORKON_HOME on line 362

correct typo in virtualenvs.rst

---

docs/scenarios/gui.rst

The description has been picked directly from https://toga.readthedocs.io.

Add toga to GUI resources

---

docs/scenarios/ci.rst
docs/starting/install/linux.rst
docs/starting/install/win.rst
docs/starting/install3/win.rst
docs/starting/installation.rst
docs/starting/which-python.rst
docs/writing/structure.rst
docs/writing/tests.rst

Probably easiest to review this by commits - each closes a single issue.
And to make that happen: closes #683, closes #806, closes #451, closes #347.

Various cross-references in tests and installation advice

---

docs/starting/install/osx.rst
docs/starting/install3/osx.rst

Update latest MacOS version name from 'Sierra' to 'High Sierra' in docs

update latest MacOS version name (High Sierra)

---

docs/scenarios/web.rst

Completes the list of DjangoCons

Add DjangoCon AU

---

docs/starting/install3/win.rst

Updates the Windows install guide to link to the current release of the installer

 Windows install link to current release

---

docs/starting/install3/win.rst

FYI, I dropped out any mentions of Python 2, because I think we can safely push Python 3 as the default Python now.

Updating to use chocolatey

---

docs/scenarios/crypto.rst

* Added GPGME bindings description and the standard encryption and
decryption example.

GPGME Python bindings

---

docs/scenarios/imaging.rst

Minor change to OpenCV example code in the import statement

Minor change to OpenCV example code

---

docs/intro/learning.rst

I've been working on free and interactive Python tutorials on [Code the blocks](https://codetheblocks.com) and thought that it would make a valuable addition to the list of tutorials on this site. Thank you for your consideration.

Added "Code the blocks" to interactive tutorial list in learning.rst

---

docs/scenarios/crypto.rst

* Added links to the new GPGME Python Bindings HOWTO.
* Added links to sample scripts written in Python 3.
* Updated the encryption and decryption example code to use the
current best practices instead of the underlying, low level
op_encrypt method (the best practices are easier and even more
pythonic).
Signed-off-by: Ben McGinnes <ben@adversary.org>

doc: crypto.rst — GPGME HOWTO update

---

docs/starting/install3/osx.rst

Fix typo in osx.rst

---

docs/scenarios/web.rst

Mention that pyramid powered pypi and makes some decisions for users providing project templates

Mention pyramid cookiecutters and pypi

---

docs/dev/virtualenvs.rst

Fix undefined labels

---

docs/scenarios/web.rst

Update web.rst to include Falcon web framework

---

docs/intro/learning.rst

Added another beginner tutorial

Added tutorial

---

docs/shipping/freezing.rst

Added hint, that py2exe looks dated.

---

docs/scenarios/web.rst

Update web.rst following #922

---

docs/_templates/layout.html
docs/_templates/sidebarintro.html

https://github.com/realpython/python-guide/issues/932 
cc @dbader

[doc website] Add nice search experience #932

---

docs/_templates/layout.html
docs/_templates/sidebarintro.html

[fix search website] Changing the position of the script (not included)

---

docs/scenarios/serialization.rst

@mpoulin, can you please look at my pull request and confirm if everything in it looks fine? I am currently working on the remaining sections of this topic and in the meantime, I wanted to run this by you or Dan to see if any changes are required to the existing structure. Thanks in advance.

issue-938: added sections in serialization for simple file, csv, yaml and json

---

docs/scenarios/web.rst

Add [FastAPI](https://github.com/tiangolo/fastapi) to the web frameworks section.

Add FastAPI to the web frameworks section

---

docs/scenarios/cli.rst

The project repo says that Clint has been archived by owner.

remove reference to Clint

---

docs/scenarios/scientific.rst

Added a description of and link to the xarray project, underneath pandas.

Add xarray to scientific section

---

docs/writing/structure.rst

Switch the Further Reading section to Python 3 link

Don't recommend Python 2 Library

---

docs/scenarios/cli.rst
docs/scenarios/gui.rst
docs/writing/structure.rst

Some of the content was quite outdated (e.g. Pyjamas has been Pyjs for quite some time), so I updated with current info. Also did some minor grammar fixes and reformatted lines to 78 characters where applicable, etc.

Updates to GUI and CLI Files

---

docs/scenarios/admin.rst
docs/scenarios/clibs.rst

- In scenarios/clibs.rst, adding StackOverflow link to explain ABI
-- In same, adding Microsoft Doc link to explain LoadLibrary
-- Minor grammar changes
-- Updating struct documentation link to use /3/ instead of /3.5/

- Minor enhancements to clibs and admin scenarios

---

docs/conf.py

- Updated the copyright to be dynamic.
- Made changes in import to adhere to PEP8

Update copyright to be dynamic

---

docs/writing/logging.rst

Feel like loguru has gained enough traction (and works so well!) as to merit inclusion at this point. Esp. when the Hitchhiker's Guide admits that the official docs on logging are a bear to read :)

add paragraph on loguru to logging section

---

docs/_templates/sidebarintro.html
docs/_templates/sidebarlogo.html

👋 team,
TL;DR: Enhance the search experience as https://pipenv.readthedocs.io/en/latest/
This PR:
- Enables async way of loading assets. It will avoid any perf issue.
- Add the search to every pages.
Let me know if you need anything

[doc website] Update the search experience

---

docs/dev/virtualenvs.rst

* Autoenv has been locked, use direnv as recommended by Autoenv

Replace Autoenv with direnv

---

docs/shipping/freezing.rst

Added installation instructions and usage for tools mentioned in Linux stubs for Freezing Your Code (https://docs.python-guide.org/shipping/freezing/). 
Fixes #977

Adding instructions in Linux stubs in section "Freezing Your Code".

---

docs/contents.rst.inc
docs/shipping/publishing.rst

Here's a first attempt at a section on hosting your project on GitHub.
It is opinionated, so it should fit right in. :)
Fixes #803.

Add a Publishing Your Code section about GitHub

---

docs/shipping/freezing.rst

I think it would be useful to show the latest release from all the tools listed in the page.

entry Latest release date added to comparison of features table

---

docs/starting/install3/linux.rst

Setup Python 3.8 on Ubuntu

---

docs/writing/tests.rst

Only needed for Python 2.6 and below

Remove section on unittest2

---

docs/writing/style.rst

I added yapf and black to the PEP 8 section about auto formatting. I highly appreciate any feedback. #931

Add auto-formatting section

---

docs/index.rst
docs/scenarios/admin.rst
docs/scenarios/ci.rst
docs/starting/which-python.rst
docs/writing/documentation.rst
docs/writing/gotchas.rst
docs/writing/license.rst
docs/writing/logging.rst
docs/writing/structure.rst
docs/writing/style.rst
docs/writing/tests.rst

It isn't anything major. I was reading through and just changed a few sentences. None of the changes should have made any change to the original meanings of the sentences.

Minor changes to few sentences.

---

docs/scenarios/web.rst

I didn't use it before, but I don't think they offer PaaS publicly now.
https://eldarion.com/

Remove Eldarion

---

docs/writing/structure.rst

Updating python 2 syntax to Python 3 in [structure section](https://docs.python-guide.org/writing/structure/)
Issue #1091

Update examples to Python 3 in structure section

---

docs/writing/style.rst

Updating python 2 syntax to Python 3 in [code style section](https://docs.python-guide.org/writing/style/)
Issue #1091

Update examples to Python 3 in code style section

---

docs/scenarios/speed.rst

Updating python 2 syntax to Python 3 in [speed section](https://docs.python-guide.org/scenarios/speed/)
Issue #1091

Update examples to Python 3 in speed section

---

docs/scenarios/gui.rst

Updating the description, url and package name for PySide.

Update PySide entry

---

docs/scenarios/admin.rst

Code refactoring and wording improvements.

Code refactoring and wording improvements for psutils.
