- docs/scenarios/json.rst
I've added the following to the JSON section:
* How to use simplejson in place of json in older versions of Python
* How to load and save JSON from/to file objects instead of strings
I've also reworded the intro paragraph a little and cleaned up the language of the simplejson paragraph.
Please take a look and tell me what you think! Thanks.
> Improve json section

- docs/writing/style.rst
See description in https://github.com/kennethreitz/python-guide/issues/525 for details.
> Revise 'consenting adult' verbiage

- docs/starting/which-python.rst
Jython 2.7 was just released. The Python-guide docs still say 2.5.
> jython version now 2.7

- docs/dev/virtualenvs.rst
I use `mkproject` more often than `mkvirtualenv` personally.  I thought it'd be valuable to present both.
> Add mkproject instructions for virtualenvwrapper

- docs/dev/env.rst
fixes #532: vim-pep8 and vim-pyflakes has been deprecated in favor for vim-flake8.
> fixes #532 added doc for vim-flake8

- docs/dev/env.rst
Current emacs no longer has ambiguous python.el. Gallina version is now the blessed standard.
> reflect unification of python in emacs.

- docs/intro/community.rst
The image for a PEP acceptance workflow was 404. I took a valid link directly from [https://www.python.org/dev/peps/pep-0001/](https://www.python.org/dev/peps/pep-0001/).
> Fixed a broken PEP acceptance workflow link.

- docs/dev/env.rst
https://github.com/jonathanslenders/ptpython/
> Add ptpython to other tools

- Readme.rst
- docs/_templates/sidebarintro.html
- docs/_templates/sidebarlogo.html
- docs/index.rst
- docs/intro/duction.rst
Best practice should not be hyphenated, I removed multiple instances where it was, I intentionally left out `_server-best-practices-ref:` (Line 177, docs/scenarios/web.rst).
Sources to support the change:
[Oxford dictionary, English](http://www.oxforddictionaries.com/definition/english/best-practice)
[Oxford dictionary, American English](http://www.oxforddictionaries.com/definition/american_english/best-practice)
[Wikipedia](https://en.wikipedia.org/wiki/Best_practice)
> Un-hyphenating best practice in multiple files

- docs/_templates/sidebarintro.html
The link for contributing - http://docs.python-guide.org/en/latest/notes/contribute.html is broken. Fixed it to point to correct link.
> Contribute link on sidebar fixed

- docs/scenarios/imaging.rst
1. Added Dive Into Python for those looking to learn Python 2 first.
2. Fix for #569
> PIL Link Fix

- docs/starting/install/osx.rst
The link on ```several ways``` specified in section http://docs.python-guide.org/en/latest/starting/install/osx/#setuptools-pip is broken.
Fixed with https://python-packaging-user-guide.readthedocs.org/en/latest/pip_easy_install/#pip-vs-easy-install
> Fix link to pip vs easy_install comparison

- docs/writing/style.rst
As discussed in #174, it's probably preferable to suggest using a set in place of a dictionary with empty values when talking about the benefits of hashtables for search speed, in "Create a length-N list of lists" in the idioms section. It seems like part of the reason dictionaries were originally used there is that this section actually bundles a few related idioms together. For clarity (and to be able to talk about search speed without being forced to use the motivating example of a collection of lists), I split this section into three:
* Create a length-N list of lists
* Create a string from a list
* Searching for an item in a collection
In the "Searching for an item in a collection" section, I replaced the dictionary with a set, and added a brief explanation on the trade-offs between …
> Resolved issue #174 by subdividing list idioms and replacing dict w/ set

- docs/dev/env.rst
#395 suggests adding a section on [pyenv](https://github.com/yyuu/pyenv), and is marked as "PR Would be Accepted".
I've added a section on pyenv under `Your Development Environment > Interpreter Tools`.  I've talked about how it lets different versions be installed side-by-side, how it allows for multiple interpreters, briefly mentioned how it works, and also suggested the use of [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv) which integrates virtualenvs into the pyenv workflow.
I haven't included demonstrations of how to use it, because none of the other sections seem to have that.
> Add a section for pyenv

- docs/scenarios/db.rst
The link for "models" in http://docs.python-guide.org/en/latest/scenarios/db/#django-orm is pointing a page that no longer exists. This changes it to point to the 'dev' version of docs in the django project.
> Change to link to point to "dev" version of documentation in Django docs

- docs/starting/which-python.rst
Plus link to relevant pep section in case of updates.
> explicitely state EOL year for python 2

- docs/starting/which-python.rst
Creates a link to the official page stating 2020 as EOL.
Fixes #588
(Sorry if this appears twice - my git-fu is weak.)
>  Add link to EOL date

- docs/starting/install/linux.rst
The latest versions of all of these distros come w/ 2.7 now.
(Reference for RHEL: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.0_Release_Notes/sect-Red_Hat_Enterprise_Linux-7.0_Release_Notes-Compiler_and_Tools-Programming_Languages.html#idp12251048 )
> Update list of distros that come with 2.7

- docs/starting/install/osx.rst
Installing XCode isn't enough - minus the commandline tools, you'll get c compiler errors when you `brew install python`.
> add note about XCode commandline tools in initial mac guide

- docs/dev/virtualenvs.rst
with virtualenv-burrito, we can have a virtualenv + virtualenvwrapper
environment by typing out a single command.
https://github.com/brainsik/virtualenv-burrito
#325
> added info for virtualenv-burrito

- docs/dev/env.rst
“in an one project” didn’t make sense. It should either be “in any project” or “in one project”.
> env.rst: fix typo

- docs/scenarios/web.rst
http://www.makotemplates.org/
Mako is the default templating language included in the pyramid
and pylons web frameworks. This includes a short info on how to
get started writing templates in Mako.
_I am not sure what to keep and what to omit._
> add Mako to templating section

- docs/scenarios/scrape.rst
This can also be thought of as a bug in lxml.
It just occurred to me that maybe I should fix that.
> use .content in lxml

- docs/dev/virtualenvs.rst
- docs/starting/install/linux.rst
- docs/starting/install/osx.rst
- docs/starting/install/win.rst
At the bottom of the installation guides for Windows, OS X, and Linux, link to the site's own version of the Virtual Environments page, instead directly linking to the version on GitHub. This is a fix for issue #656.
> Link to internal Virtual Environments page from install pages

- docs/scenarios/xml.rst
In the xmltodict example, the xml is loaded in the variable obj but is later referenced as doc.
Fixed by renaming obj to doc
> Fix varibable name in XML parsing scenario

- docs/writing/style.rst
Deprecated xrange() in Python 3
Reverted back previous commit of changing xrange. Added a note instead.
> A note for xrange() use in Python 3. Issue #665

- docs/writing/documentation.rst
The current link to pycco returns a 404.  It looks project was moved into its own github account.
> Updated documentation.rst - pycco homepage moved

- docs/scenarios/web.rst
I don't think we should compare Gondor and Heroku simply based on user base. While it's true Heroku is the largest PaaS and Gondor is run by a small company, I think we should be a bit more explicit about how Gondor tries to differentiate themselves. Per conservations with @paltman, Gondor seems to much more of a partnership with companies aiming to launch Django/Pinax applications than a simple hosting company.
Including @jtauber @brosner, in no way do I wish to speak for Gondor or Eldarion :)
> Clarify Gondors stance

- docs/scenarios/scrape.rst
the old link 404's, so I did a quick search and found the W3C XPath tutorial and replaced the link.
> change W3C link to the XPath Tutorial

- docs/writing/reading.rst
Using `.. raw:: html` directive.
I experimented with the spinxcontrib.youtube plugin, but it is buggy. See [my youtube-sphinxcontrib branch](https://github.com/serra/python-guide/commit/530d4910432d9a039cd6702b14515be09613d867), so I opted for this raw html approach instead.
I have not tested targets other than `html` and `singlehtml`.
> Include Youtube video of reading code 

- docs/scenarios/ci.rst
afaik Mule is an Enterprise Service Bus, which can be useful in enterprise application integration scenarios, but imo an ESB is not useful in the context of continuous integration of Python programs.
If it ended up here by accident, let's remove it. If not, please reveal its intended use in CI scenarios.
> I fail to see how Mule would help in Continuous Integration scenarios

- docs/starting/install/osx.rst
As can be seen on the [Homebrew website](http://brew.sh/), it seems that
Homebrew is now recommending that you install Homebrew by calling
`/usr/bin/ruby` instead of just `ruby`.
> Updates command for installing Homebrew

- docs/writing/tests.rst
Quoting https://www.python.org/dev/peps/pep-0257/#one-line-docstrings
> "The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ..."."
> Changed summary line of docstring to follow PEP 0257

- docs/scenarios/crypto.rst
Python 3.2 support has been dropped from pyca/cryptography as of April 2015. https://github.com/pyca/cryptography/pull/1846
> pyca/cryptography no longer supports Python 3.2.

- docs/writing/logging.rst
dictConfig expects a special `root` key *outside* of the `loggers` subdictionary in order to configure the root logger. I've tried the existing example code on python 2.7.5 and 3.5.1, and in neither case does the final log line produce any output (because the root logger remains set to `looging.WARN` by default). 
Changing the example to use the `root` key causes the log message to appear properly.
The `root` key is explained in PEP391: https://www.python.org/dev/peps/pep-0391/#dictionary-schema-detail
> Fix incorrect dictConfig example

- docs/writing/structure.rst
Currently, this sample Makefile has problems if there are any
files/directories named init or test in the same directory as the
makefile. This commit adds a phony to the sample Makefile so that these
targets are not treated as files.
> Don't treat targets as files

- docs/writing/structure.rst
.PHONY should be followed by a colon in the Makefile
> Fix .PHONY target rule

- docs/writing/structure.rst
Memoization, while a 'big word' is a pretty simple concept, and everyone knows what caching is. While caching isn't strictly memoization, I've included a link to wikipedia's overview of it (which is very readable without understanding a lot of terminology)
I'm reasonably sure that this improves readability and content without distracting from the overall flow of the passage. I'd love comments.
> fix memoization typo, link to wikipedia's overview

- docs/_templates/sidebarintro.html
- docs/_templates/sidebarlogo.html
- docs/dev/virtualenvs.rst
- docs/intro/learning.rst
- docs/scenarios/ci.rst
- docs/scenarios/clibs.rst
- docs/scenarios/db.rst
- docs/scenarios/gui.rst
- docs/scenarios/imaging.rst
- docs/scenarios/json.rst
- docs/scenarios/web.rst
- docs/shipping/packaging.rst
- docs/starting/install/osx.rst
- docs/writing/tests.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- docs/scenarios/admin.rst
It's already mentioned in the first Buildout paragraph that the tool is built with Python.
> Remove redundant statement

- docs/starting/installation.rst
The linked page is general to Linux, and specifically mentions CentOS, Fedora, RHEL and Ubuntu. It does not contain any information that is specific to Ubuntu only.
> Rename overly specific link

- docs/scenarios/speed.rst
This todo can be removed, since information about Numba is included under [scenarios/scientific](http://docs.python-guide.org/en/latest/scenarios/scientific/#numba).
> Removes Numba todo

- docs/writing/documentation.rst
PEP 257 says:
> The docstring is a phrase ending in a period. It prescribes the function or method's effect as a command ("Do this", "Return that"), not as a description; e.g. don't write "Returns the pathname ...".
> Fixed example docstring

- CONTRIBUTING.md
These instructions detail how to build and preview changes the contributor has made as it would appear on the actual site.
This is very easy to setup provided you have python3 (http.server is called SimpleHTTPServer in python2). This seems to be a good quick way to test files visually (which would avoid screw ups like mine).
> include instructions to preview changes in CONTRIB

- docs/writing/structure.rst
the markdown was messed up, I forgot to add two underscores to the end of the memoization URL. as it is currently, it's just italicized.
Sorry!
> amending previous submission, fixing markdown

- docs/intro/learning.rst
The website rafekettler.com is down.
Reference: https://github.com/RafeKettler/magicmethods/issues/55
> updated a broken link to Python Magic Methods

- docs/dev/virtualenvs.rst
- docs/starting/install/osx.rst
- docs/starting/install3/osx.rst
- docs/starting/installation.rst
A new Python user hardly needs to know that easy_install ever existed.  
Also addresses #676 for OS X.  Open to suggestions.
> Removed references to Setuptools/easy_install in favor of pip.  

- docs/scenarios/cli.rst
The Python CLI library Click is listed as "upcoming" when it is in fact stable. I think this scares some people away who might be well served by using it.
http://click.pocoo.org/6/
> Click is stable - not upcoming

- docs/scenarios/web.rst
Gondor has changed name, it’s now called [Eldarion](http://eldarion.cloud). I haven’t used it myself, but I thought I would update the page.
> Update section about Gondor

- docs/scenarios/admin.rst
Since Google Code is defunct, the new homepage for `psutil` is on GitHub.  I've updated the link, nothing more.
> Update psutil project page to not use Google Code

- docs/scenarios/scrape.rst
The link to the W3 schools XPath tutorial in the the [HTML Scraping](http://docs.python-guide.org/en/latest/scenarios/scrape/) was broken. The link, <http://www.w3schools.com/xsl/xpath_intro.asp>, gave a 404, and was changed to <http://www.w3schools.com/xml/xpath_intro.asp>.
> Broken link: W3 Schools XPath Tutorial

- docs/writing/structure.rst
To import the package in `tests/context.py` one should use:
```python
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
```
rather than:
```python
sys.path.insert(0, os.path.abspath('..'))
```
This was already changed in [kennethreitz/samplemod](https://github.com/kennethreitz/samplemod/blob/master/tests/context.py), but not in the guide itself.
Explanation:
According to the [docs](https://docs.python.org/3.6/library/os.path.html) `os.path.abspath(path)` is equivalent to: `normpath(join(os.getcwd(), path))`.
`os.getcwd()` returns the path from where the Python interpreter was called, not the location of the executed file:
```bash
> tree dir1
dir1
└── dir2
└── dir3
└── rel_path.py
> cat dir1/rel_path.py
import os.path
print(os.path.abspath('..')) …
```
> tests: use __file__ for package import

- docs/writing/structure.rst
New to python and thought this was an error.  Upon further inspection it seems it does not make any functional difference.  Still I propose it to make the example visually consistent.
> Indentation typo

- docs/scenarios/web.rst
The "<!" before template extension statement is unnecessary and also breaks code highlighting.
> Remove junk in Jinja code block

- docs/writing/tests.rst
pytest site url was brokenly pointing to https://docs.pytest.org/latest/.
> pytest url fix

- docs/dev/env.rst
- docs/writing/style.rst
See https://github.com/PyCQA/pycodestyle/issues/466. Pointing towards the `pep8` tool risks leading users to outdated versions of the tool (the last `pep8` version is 1.7.0 from January 2016; the currently latest `pycodestyle` version is 2.3.0).
> `pep8` is nowadays called `pycodestyle`

- docs/starting/install/linux.rst
- docs/starting/install3/linux.rst
- docs/starting/installation.rst
* Fedora does not come with Python 2 pre-installed since Fedora 23
* RHEL with Python 2.4 is no longer supported (section removed)
* Added Fedora installation instructions for Python 3.6 as well
* Be carefull about /usr/bin/pip
> Update the Linux installation instructions to reflect Fedora

- docs/shipping/freezing.rst
The link to the PyInstaller was broken. I added the current link to the stable documentation.
> fixing link to manual of PyInstaller.

- docs/starting/install3/win.rst
- docs/writing/structure.rst
I have added to the relevant paragraph of the guide the very good answer that I received to my question in issue https://github.com/kennethreitz/python-guide/issues/828 regarding the use of underscores in module naming.
I also slightly lengthened an underline for the Python 3 on Windows title so Sphinx will breathe easier.
This project has been super helpful to me. Thank you!
> Clarification for Module Naming

- docs/writing/gotchas.rst
Add documentation to show how to keep `.pyc` files when working with a version control system. This will hopefully complement the existing subsections of `.pyc` files in the Gotchas page.
^_^
> Add version control ignores to gotchas

- docs/starting/install/osx.rst
Homebrew no longer sets pip.
See 5 executable names in https://docs.brew.sh/Homebrew-and-Python.html
python points to the macOS system Python (with no manual PATH modification)
python2 points to Homebrew’s Python 2.7.x (if installed)
python3 points to Homebrew’s Python 3.x (if installed)
pip2 points to Homebrew’s Python 2.7.x’s pip (if installed)
pip3 points to Homebrew’s Python 3.x’s pip (if installed)
>  Changes in how homebrew installs Python on Mac OSX

- docs/starting/install3/osx.rst
Homebrew no longer sets `pip`.
See 5 executable names in https://docs.brew.sh/Homebrew-and-Python.html
* `python` points to the macOS system Python (with no manual PATH modification)
* `python2` points to Homebrew’s Python 2.7.x (if installed)
* `python3` points to Homebrew’s Python 3.x (if installed)
* `pip2` points to Homebrew’s Python 2.7.x’s pip (if installed)
* `pip3` points to Homebrew’s Python 3.x’s pip (if installed)
> Changes in how homebrew installs Python on Mac OSX

- docs/starting/install3/linux.rst
no more bellowing required by reader.
> Fixing typos in installation guide for Linux

- docs/starting/install3/linux.rst
When following the current instructions on ubuntu 16.04 LTS I got the following feedback:
```
~$ sudo add-apt-repository ppa:fkrull/deadsnakes
Please use the new repository at
https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
instead!
More info: https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes
Press [ENTER] to continue or ctrl-c to cancel adding it
```
This PR updates the repo location.
> deadsnakes repository change

- docs/dev/env.rst
Addresses #869 - Microsoft now maintains the Python extension for VS Code, so the extension page's URL changed.
> Fix VS Code extension link

- docs/starting/install3/osx.rst
I noticed that the next page, [Pipenv & Virtual Environments](http://docs.python-guide.org/en/latest/dev/virtualenvs/), re-enforces that `python` will be assumed to invoke the Python 3 interpreter and is Highly Preferred. The last mention on [Installing Python 3 for OSX](http://docs.python-guide.org/en/latest/starting/install3/osx/#working-with-python-3) leaves `python` referencing the OSX System Python interpreter (2.7.10 for high Sierra). 
I honestly do not know if this is the "correct" way to configure this default. It looks like brew is cautious about symlinking over the native Python 2.7.10 (High Sierra) and they might have good reason. 
All of my projects are Python 3 now, so i'm ready to "make it ~facebook~ PATH official with Python 3" - as I think the documentation makes …
> (osx) how to make `python` reference `python3`

- docs/dev/pip-virtualenv.rst
The "Further Configuration of Pip and Virtualenv" contains a subsection about configuring caching in pip. This is mostly obsolete since pip caches by default and without any need for configuration since version 6.0. This update is meant to account for this.
This PR fixes #877
> Update information about pip caching

- docs/writing/structure.rst
Right now that link to the tests section doesn't get rendered as an HTML link, but instead the rst markup shows in the rendered HTML, like this:
> Fix link to the tests section

- docs/starting/install/osx.rst
- docs/starting/install3/osx.rst
The default __python__ is now Python 3.
* https://docs.brew.sh/Homebrew-and-Python
>  Homebrew has changed how Python is installed 

- docs/writing/reading.rst
Remove a non-contextual embedded video that itself has multiple errors.  It confuses things, at best.
> Remove non-contextual embedded video.

- docs/writing/style.rst
The section on filtering lists now points out some differences between Python 2.x and 3.x and how to work around them.
I also discuss the advantages of iterators vs. creating temporary lists.
> Issue 796 resolved

- docs/scenarios/cli.rst
* Add a section on [Python Fire](https://github.com/google/python-fire/)
in the CLI scenario.
Signed-off-by: mr.Shu <mr@shu.io>
> add: Section on `fire` in CLI scenario

- docs/starting/install3/osx.rst
Just a minor style fix for a couple mis-capitalized occurrences of "Homebrew".
> Capitalize "Homebrew" consistently"

- docs/scenarios/gui.rst
- docs/shipping/packaging.rst
- docs/starting/install/osx.rst
- docs/starting/install3/osx.rst
- docs/starting/install3/win.rst
Apple styles it as "Xcode" with a lower-case "c". This PR updates the OS X installation section to consistently use "Xcode" instead of "Code". Also fixes a couple "OSX"s with missing spaces.
> Style it "Xcode", not "XCode"

- docs/dev/env.rst
- docs/dev/pip-virtualenv.rst
- docs/starting/install/osx.rst
- docs/starting/install3/osx.rst
The Guide currently uses a mix of "Unix" and "UNIX" stylings. This PR makes them all "Unix", which seems to be the more modern usage.
> Use "Unix" instead of "UNIX" consistently

- docs/dev/env.rst
- docs/intro/learning.rst
- docs/notes/styleguide.rst
- docs/writing/documentation.rst
Fixes https://github.com/realpython/python-guide/issues/838
Standardizes on American English by adding a note in the Guide Style Guide and converting a couple Britishisms to American usage.
> Standardize on American English for the Guide

- docs/writing/structure.rst
This passage talks about `import` copying names into the global namespace. But doesn't it copy names into the calling module's namespace instead?
> Use "caller" instead of "global" to describe where imports go

- docs/writing/tests.rst
No comma before "and": https://www.grammarly.com/blog/comma-before-and/
> Fix grammar mistake

- docs/dev/virtualenvs.rst
Fixes a couple shell session code blocks to use `console` instead of `bash`, as specified in the Style Guide.
> Use `console` lexer, not `bash`, for shell sessions

- docs/writing/structure.rst
- docs/writing/style.rst
Fixes #968. 
This PR removes the recommendation to use `map` over list comprehensions from the _Structuring Your Project_ page. 
This PR also removes most discussion about `map` and `filter` from the _Code Style_ page, recommending instead generator functions and list comprehensions (as discussed in #968). Personally, I value opinionated and prescriptive guides when learning something new, but feel free to push back if the old material should stay. 
Also made some minor edits, slightly expanded the discussion on list vs iterators, and added a couple of examples.
> Prefer list comprehensions over map and filter

- docs/starting/install/osx.rst
- docs/starting/install3/osx.rst
The Installing on OS X sections say this:
> The latest version of Mac OS X, High Sierra, comes with Python 2.7 out of the box.
There's probably no need to qualify that statement with "High Sierra". OS X has shipped with 2.7 at least as far back as 10.7 Lion from 2011.
> Don't qualify OS X version when saying what Python version it ships with

- docs/dev/virtualenvs.rst
Before, http://python-requests.org would redirect to http://docs.python-requests.org/en/master/
Now, page links to http://docs.python-requests.org/en/master/ directly.
> python-requests.org redirect

- docs/_templates/sidebarintro.html
- docs/conf.py
- docs/dev/env.rst
- docs/dev/virtualenvs.rst
- docs/intro/duction.rst
- docs/intro/learning.rst
- docs/intro/news.rst
- docs/notes/contribute.rst
- docs/scenarios/cli.rst
- docs/scenarios/client.rst
- docs/scenarios/db.rst
- docs/scenarios/network.rst
- docs/scenarios/scientific.rst
- docs/scenarios/speed.rst
- docs/scenarios/xml.rst
- docs/shipping/freezing.rst
- docs/shipping/packaging.rst
- docs/starting/install/linux.rst
- docs/starting/install/osx.rst
- docs/starting/install/win.rst
- docs/starting/install3/linux.rst
- docs/starting/install3/osx.rst
- docs/starting/install3/win.rst
- docs/writing/logging.rst
- docs/writing/style.rst
- docs/writing/tests.rst
Fix redirected and broken links.
Fixes https://github.com/realpython/python-guide/issues/928.
> Fix redirected and broken links

- docs/dev/virtualenvs.rst
- Make the windows virtualenv example slightly more clear.
- Fix inconsistency with virtualenv project folder naming.
- Make a couple minor grammar fixes.
> Minor Inconsistency and Grammar Fixes

- docs/notes/styleguide.rst
- docs/starting/install/win.rst
- docs/starting/install3/win.rst
The Windows console code blocks are formatted with the `doscon` Pygments lexer. That's the Unix console. How about formatting them with the Windows-specific `doscon` and `powershell` lexers?
> Format Windows console examples with `doscon`or `powershell`

- docs/scenarios/crypto.rst
Unmaintained package with CVE might not be a good help
https://www.cvedetails.com/product/22441/Dlitz-Pycrypto.html?vendor_id=11993
I also share the opinion of the author that pycrypto and its fork may promote insecure usage (like AES::ECB)
https://theartofmachinery.com/2017/02/02/dont_use_pycrypto.html
> you don't let friends use pycrypto

- docs/scenarios/db.rst
Hey, I wondered if I could talk you into including [PugSQL](https://pugsql.org). 
It's a Python take on the popular [HugSQL](https://www.hugsql.org/) Clojure library, and I've been taking pains to make it well documented. 
There wasn't any obvious order to the list that I could discern, so I stuck it underneath `Records`. It's philosophically closest to `Records`, and `Records` got there first. 
I tested my changes locally and they look fine:
And I'm pretty sure I followed everything in the style guide.
> Adding pugsql to the database guide

- docs/scenarios/speed.rst
This fixes the following build warning:
python-guide/docs/scenarios/speed.rst:397: WARNING: Unknown target name: "stack overflow post".
> Fix broken reference to Stack Overflow post

- docs/writing/structure.rst
Adding a link to the original essay. I think it's important to add the data of the recommendation as well since a lot of things happened since then. I guess the need to add the date is pointing out that the section could need a refresh.
> Add link to the original essay

- docs/shipping/packaging.rst
In the sample local web-server to serve packages, the command-line has been adapted to Python-3,
Python-2 module `SimpleHTTPServer` has moved to `http.server`.
> Use PY3 http.server instead of SimpleHTTPServer

- docs/dev/virtualenvs.rst
Changed `https://docs.pipenv.org/` -> `https://pipenv.kennethreitz.org/`
> Fixed broken link to Pipenv documentation

- docs/writing/style.rst
The link to the pep20_by_example.pdf is wrong and points to a 404 page. I have replaced the old link with a new link pointing to the Github repo from the creator of the original presentation. I did not link explicitly the pdf in the repo, to allow the visitors to see more content.
> Fixed link to non-existing pep20_by_example.pdf

- docs/writing/structure.rst
The diveinto.org link is broken when I try it.  I found that https://diveinto.org/python3/table-of-contents.html works but the https://diveintopython3.net/ is shorter and appears less broken to someone reading the url for the first time.  The table of content at this updated address looks the same as what I found on the web.archive.org for the diveinto.org link.
> Update diveinto link

- docs/notes/styleguide.rst
- docs/writing/documentation.rst
Old Sphinx links were updated to (hopefully) point to their modern equivalents.
Fixes #1023
> Fix broken Sphinx Links

- docs/intro/learning.rst
http://propython.com/ is no longer owned by Marty Alchin (author of Pro Python), thus it is more appropriate to link to the direct selling link of the book.
> Fixed Pro Python link from unused domain to seller

- docs/intro/learning.rst
The GitHub repo is much more uptodate.
It has a working Python 3 version with fixed and updated tests.
> Update the link to Python Koans

- docs/dev/env.rst
As mentioned in #1021 , Visual Studio Code is not an IDE, therefore, moving it from "IDEs" to "Text Editors" and correcting the mis-spellings (e.g.: "Visual Studio Code IDE" to "Visual Studio Code")
> #1021 Moved VS Code to Text Editor

- docs/starting/which-python.rst
Since Python2 reached the end of its life in January, we need to update the page "Picking a Python Interpreter" accordingly.
Also, some of the links were broken.
> Fixes for Python 2 End of Life

- docs/starting/install3/osx.rst
if you use the older `ruby` command, the brew installer throws the following warning in terminal:
```
Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```
This is the official method for installing homebrew per their [homepage](https://brew.sh/) and this [discussion](https://medium.com/@itchyny/homebrew-installer-in-bash-is-released-335bbc2b9bce)
> update brew download link

- docs/scenarios/json.rst
The simplejson library was only needed for Python 2.5 and earlier.
Update documentation link to Python 3.
> Remove simplejson from guide

- docs/writing/structure.rst
Kenneth Reitzs essay Repository Structure and Python was moved to https://kennethreitz.org/essays/2013/01/27/repository-structure-and-python
The old URL hit a 404.
> kennethreitzs essay repository-structure-and-python new URL

- docs/scenarios/scrape.rst
Updating python 2 syntax to Python 3 in [scrape section](https://docs.python-guide.org/scenarios/scrape/)
Issue #1091
> Update examples to Python 3 in scrape section

- docs/intro/learning.rst
Updated broken link for "Expert Python Programming" book in `Learning Python` section
> docs: fix Expert Python Programming book link

- docs/writing/reading.rst
Link currently points to a tablib fork and not to the original repo (https://github.com/jazzband/tablib). Fork doesn't look maintained and is behind the original repo
Changing link to use https://github.com/jazzband/tablib
> Replacing Tablib fork with the original repo

- docs/dev/virtualenvs.rst
- docs/scenarios/client.rst
- docs/scenarios/scrape.rst
- docs/writing/style.rst
This is a quick follow up from psf/requests#6140. This PR fixes dead links by moving it to https://requests.readthedocs.io/en/latest/ which will be the primary domain for the project going forward. Please let me know if there are any questions/concerns.
> Update Requests documentation links

- docs/scenarios/xml.rst
I recently discovered another excellent XML library worth to be listed here.
> add section for xmlschema

- docs/scenarios/admin.rst
The last version has been released 8 years ago: [https://en.wikipedia.org/wiki/Shinken_(software)](Wikipedia)
> fix: remove Shinken from the admin part, because Shinken is dead 
